image: node:lts-alpine

stages:
  - testing
  - packaging
  - publishing

npm outdated:
  stage: testing
  script:
    - npm ci
    - npm outdated
  allow_failure: true

security scan:
  stage: testing
  script:
    - npm audit --production
  allow_failure: false

test:
  stage: testing
  script:
    - RUN_IN_CI=yes npm it
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  artifacts:
    paths:
      - coverage/

package:
  stage: packaging
  script:
    - npm pack
  artifacts:
    paths:
      - ./*.tgz

publish:
  stage: publishing
  only:
    - tags
    - triggers
  script:
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
    - npm publish
  environment:
    name: npm
    url: https://www.npmjs.com/package/gulp-web-dependencies
